const tagsMap = new Map()
tagsMap.set('1', { ename: 'brand', cname: '品牌' })
tagsMap.set('2', { ename: 'client', cname: '客戶'})
tagsMap.set('3', { ename: 'product manager', cname: '產品企劃'})
tagsMap.set('4', { ename: 'product design', cname: '產品設計'})
tagsMap.set('5', { ename: 'design', cname: '設計'})
tagsMap.set('6', { ename: 'engineering', cname: '工程'})
tagsMap.set('7', { ename: 'production', cname: '生產'})
tagsMap.set('8', { ename: 'photography', cname: '攝影'})
tagsMap.set('9', { ename: 'date', cname: '日期'})
tagsMap.set('10', { ename: 'ux design', cname: '使用經驗設計'})
tagsMap.set('11', { ename: 'ui design', cname: '介面設計'})
tagsMap.set('12', { ename: 'illustration', cname: '插畫'})
tagsMap.set('13', { ename: 'music', cname: '音樂'})
tagsMap.set('14', { ename: 'programming', cname: '程式開發'})
tagsMap.set('15', { ename: 'print', cname: '印刷'})
tagsMap.set('16', { ename: 'planning', cname: '企劃'})
tagsMap.set('17', { ename: 'model', cname: '模特兒'})
tagsMap.set('18', { ename: 'cooperation', cname: '合作'})

module.exports = tagsMap