const tagsMap = new Map()
tagsMap.set('1', { ename: 'Brand', cname: '品牌' })
tagsMap.set('2', { ename: 'Client', cname: '客戶'})
tagsMap.set('3', { ename: 'Product manager', cname: '產品企劃'})
tagsMap.set('4', { ename: 'Product design', cname: '產品設計'})
tagsMap.set('5', { ename: 'Design', cname: '設計'})
tagsMap.set('6', { ename: 'Engineering', cname: '工程'})
tagsMap.set('7', { ename: 'Production', cname: '生產'})
tagsMap.set('8', { ename: 'Photography', cname: '攝影'})
tagsMap.set('9', { ename: 'Date', cname: '日期'})
tagsMap.set('10', { ename: 'UX design', cname: '使用經驗設計'})
tagsMap.set('11', { ename: 'UI design', cname: '介面設計'})
tagsMap.set('12', { ename: 'Illustration', cname: '插畫'})
tagsMap.set('13', { ename: 'Music', cname: '音樂'})
tagsMap.set('14', { ename: 'Programming', cname: '程式開發'})
tagsMap.set('15', { ename: 'Print', cname: '印刷'})
tagsMap.set('16', { ename: 'Planning', cname: '企劃'})
tagsMap.set('17', { ename: 'Model', cname: '模特兒'})
tagsMap.set('18', { ename: 'Cooperation', cname: '合作'})

module.exports = tagsMap