const workerMap = new Map()
workerMap.set('1', { ename: 'simple cocoon', cname: 'simple cocoon' })
workerMap.set('2', { ename: 'SMILOGY', cname: '微笑地球' })
workerMap.set('3', { ename: 'Luzstudio', cname: 'Luzstudio' })
workerMap.set('5', { ename: 'Chewei Chen', cname: '陳哲瑋' })
workerMap.set('6', { ename: 'cheermoon', cname: '福月有限公司' })
workerMap.set('7', { ename: 'Seyoua', cname: 'Seyoua' })
workerMap.set('8', { ename: 'Pcare', cname: 'Pcare' })
workerMap.set('9', { ename: 'Eureka', cname: '收藏家' })
workerMap.set('10', { ename: 'unipapa', cname: 'unipapa' })

workerMap.set('11', { ename: 'chill chill', cname: '巧巧' })
workerMap.set('12', { ename: 'OZARK', cname: 'OZARK' })
workerMap.set('13', { ename: '3M', cname: '3M' })
workerMap.set('14', { ename: 'uanuan', cname: '源源鋼藝' })

workerMap.set('16', { ename: 'LanVece', cname: '一步青山' })
workerMap.set('17', { ename: 'Lingda', cname: 'Lingda' })
workerMap.set('18', { ename: 'cremove', cname: '創動感' })
workerMap.set('19', { ename: 'minds', cname: '邁得思' })
workerMap.set('20', { ename: 'Flora Piano', cname: '寬域工作室' })

workerMap.set('21', { ename: 'Li Jin Industrial', cname: '立津國際開發' })
workerMap.set('22', { ename: 'Above', cname: '逸志科技' })
workerMap.set('23', { ename: 'Chihyi CC', cname: '林芷伊' })
workerMap.set('24', { ename: 'Shan Yao', cname: '姚杉' })
workerMap.set('25', { ename: 'Flora', cname: 'Flora' })
workerMap.set('26', { ename: 'Eric Chen', cname: '陳聖欣' })
// workerMap.set('27', { ename: '羅代團隊', cname: '羅代團隊' })
workerMap.set('28', { ename: 'Tzuyao Yang', cname: '楊子瑤' })
workerMap.set('29', { ename: 'Chaocheng Wang', cname: '王照程' })
workerMap.set('30', { ename: 'Kenny Liao', cname: '廖季農' })

workerMap.set('31', { ename: 'Wenfu Lai', cname: '賴文復' })
workerMap.set('32', { ename: 'Hsiutzu Fang', cname: '方秀慈' })
workerMap.set('33', { ename: 'AIFA', cname: '艾法科技' })
workerMap.set('34', { ename: 'Chili Development', cname: '騏勵開發' })
workerMap.set('35', { ename: 'Chifan Chung', cname: '鍾濟凡' })
workerMap.set('36', { ename: 'Kuanchen Chen', cname: '陳冠辰' })
workerMap.set('37', { ename: 'Zihci Lin', cname: '林子棋' })
workerMap.set('38', { ename: 'Yaojen Chang', cname: '張耀仁' })
workerMap.set('39', { ename: 'Peiju Chan', cname: '詹佩茹' })
workerMap.set('40', { ename: 'Adam', cname: 'Adam' })

workerMap.set('41', { ename: 'sparospace', cname: '威雀科技' })
workerMap.set('42', { ename: 'Veronica Rehab', cname: 'Veronica Rehab' })
workerMap.set('43', { ename: 'Yuchi Huang', cname: '黃毓祺' })
workerMap.set('44', { ename: 'Eroam Tech Co.', cname: '義峰國際' })
workerMap.set('45', { ename: 'GOODGLAS', cname: '好玻' })
workerMap.set('46', { ename: 'pirre paul‘s', cname: '羅代有限公司' })
workerMap.set('47', { ename: 'NIHAO', cname: '泥好製所' })
workerMap.set('48', { ename: 'GEKKO', cname: '掛酷' })
workerMap.set('49', { ename: 'Transway Plastic', cname: '創維塑膠' })
workerMap.set('50', { ename: 'sparo\'s', cname: 'sparo\'s' })

workerMap.set('51', { ename: '2021', cname: '2021' })
workerMap.set('52', { ename: '2020', cname: '2020' })
workerMap.set('53', { ename: '2019', cname: '2019' })
workerMap.set('54', { ename: '2018', cname: '2018' })
workerMap.set('55', { ename: '2017', cname: '2017' })
workerMap.set('56', { ename: '2016', cname: '2016' })
workerMap.set('57', { ename: '2015', cname: '2015' })
workerMap.set('58', { ename: '2014', cname: '2014' })
workerMap.set('60', { ename: 'Aaron Yen', cname: '正淵' })

workerMap.set('61', { ename: 'Yichang Chen', cname: '陳奕璋' })
workerMap.set('62', { ename: '（未知）', cname: '（未知）' }) // FIXME:
workerMap.set('63', { ename: 'Switch Taipei', cname: 'Switch Taipei' })
workerMap.set('64', { ename: 'Jason Xu', cname: '許閎傑' })

module.exports = workerMap